version: '3.7' 
services:
  slurmjupyter:
        image: vanillajupyter
        hostname: slurmjupyter
        volumes:
                - shared-vol:/home/root
                - shared-env:/env/open-ce
                - shared-data:/data
                - conda-dir:/miniconda/

        ports:
                - 8888:8888
        # deploy:
        #   resources:
        #     reservations:
        #       devices:
        #         - driver: nvidia
        #           capabilities: [gpu]
  slurmmaster:
        image: vanillamaster
        hostname: slurmmaster
        volumes:
                - shared-vol:/home/root
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        image: vanillanode
        hostname: slurmnode1
        volumes:
                - shared-vol:/home/root
                - shared-env:/env/open-ce
                - shared-data:/data
                - conda-dir:/miniconda/

        links:
                - slurmmaster
  slurmnode2:
        image: vanillanode
        hostname: slurmnode2
        volumes:
                - shared-vol:/home/root
                - shared-env:/env/open-ce
                - shared-data:/data
                - conda-dir:/miniconda/

        links:
                - slurmmaster
  slurmnode3:
        image: vanillanode
        hostname: slurmnode3
        volumes:
                - shared-vol:/home/root
                - shared-env:/env/open-ce
                - shared-data:/data
                - conda-dir:/miniconda/

        links:
                - slurmmaster

  slurmnode4:
        image: vanillanode
        hostname: slurmnode4
        volumes:
                - shared-vol:/home/root
                - shared-env:/env/open-ce
                - shared-data:/data
                - conda-dir:/miniconda/

        links:
                - slurmmaster
volumes:
        shared-env:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '/home/user/miniconda3/envs/pypytorch'
        shared-data:
        shared-vol:
        conda-dir:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'bind'
                        device: '/home/user/miniconda3'

version: '3'
