version: '3.7' 
services:
  slurmjupyter:
        image: st7ma784/slurmjupyter:latest
        hostname: slurmjupyter
        restart: always
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        #links:
        #  - slurmmaster
        volumes:
                - shared-vol:/home/root
                #- shared-env:/root/miniconda3/envs/env
        ports:
                - 8888:8888
     
  slurmmaster:
        image: st7ma784/slurm-master:latest
        hostname: slurmmaster
        restart: always
        volumes:
                - shared-vol:/home/root/
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        image: st7ma784/slurm-node:latest
        hostname: slurmnode1
        restart: always 
        volumes:
                - shared-vol:/home/root/
        links:
                - slurmmaster
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  capabilities: [gpu]

volumes:
  shared-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/DATA'
#shared-env:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/user/miniconda3/envs/open-ce'
