services:
  slurmjupyter:
        image: vanillajupyter
        hostname: slurmjupyter
        volumes:
                - shared-vol:/home/root
        ports:
                - 8888:8888
        deploy:
        #   resources:
        #     reservations:
        #       devices:
        #         - driver: nvidia
        #           capabilities: [gpu]
  slurmmaster:
        image: vanillamaster
        hostname: slurmmaster
        volumes:
                - shared-vol:/home/root
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        image: vanillanode
        hostname: slurmnode1
        volumes:
                - shared-vol:/home/root
        links:
                - slurmmaster
  slurmnode2:
        image: vanillanode
        hostname: slurmnode2
        volumes:
                - shared-vol:/home/root
        links:
                - slurmmaster
  slurmnode3:
        image: vanillanode
        hostname: slurmnode3
        volumes:
                - shared-vol:/home/root
        links:
                - slurmmaster
  slurmnode4:
        image: vanillanode
        hostname: slurmnode4
        volumes:
                - shared-vol:/home/root
        links:
                - slurmmaster

  slurmnode5:
        image: vanillanode
        hostname: slurmnode5
        volumes:
                - shared-vol:/home/root
        links:
                - slurmmaster
  slurmnode6:
        image: vanillanode
        hostname: slurmnode6
        volumes:
                - shared-vol:/home/root
        links:
                - slurmmaster
volumes:
        shared-vol:
        
    driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/DATA'

version: '3'
