version: '3.7' 
services:
  slurmjupyter:
        image: st7ma784/jupyter:latest
        hostname: slurmjupyter
        volumes:
                - shared-vol:/home/root/
        ports:
                - 8888:8888
        # deploy:
        #   resources:
        #     reservations:
        #       devices:
        #         - driver: nvidia
        #           capabilities: [gpu]
  slurmmaster:
        image: st7ma784/master:latest
        hostname: slurmmaster
        volumes:
                - shared-vol:/home/root/
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        image: st7ma784/node:latest
        hostname: slurmnode1

        volumes:
                - shared-vol:/home/root/
        links:
                - slurmmaster
        # deploy:
        #   resources:
        #     reservations:
        #       devices:
        #         - driver: nvidia
        #           capabilities: [gpu]
volumes:
  shared-vol:



